name: 'Terragrunt Setup'
description: 'Setup Terraform and Terragrunt'

inputs:
  terraform-version:
    description: 'Terraform version'
    required: true
  terragrunt-version:
    description: 'Terragrunt version'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
  aws-role:
    description: 'AWS role to assume'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: GitHubActions-Terraform

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false

    - name: Check Terraform formatting
      shell: bash
      run: terraform fmt -check -recursive

    - name: Terragrunt Setup
      shell: bash
      run: |
        wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v${{ inputs.terragrunt-version }}/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
        terragrunt --version
